[project]
name = "russian-stocks-prediction-ml-dl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncio>=4.0.0",
    "pandas>=1.5.0",
    "psycopg2>=2.9.11",
    "requests>=2.28",
    "sqlalchemy>=2.0.44",
    "tinkoff-investments>=0.2.0b117",
    "SQLAlchemy>=1.4",
    "psycopg2-binary>=2.9",
    "tpulse>=0.1.9",
    "tqdm>=4.67.1",
    "matplotlib>=3.10.7",
]
