[project]
name = "russian-stocks-prediction-ml-dl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncio>=4.0.0",
    "pandas>=2.3.3",
    "psycopg2>=2.9.11",
    "requests>=2.32.5",
    "sqlalchemy>=2.0.44",
    "tinkoff-investments>=0.2.0b117",
]
